### ISSUE TITLE
Converting Class Variable to a Factor - Chapter 5

### ISSUE THREAD

**Issue by jmanacup** [PacktPublishing/Machine-Learning-with-R-Third-Edition#3]
Good day!

I am reading the `Machine Learning with R` and encountered that in chapter 5 of the book, running the code below outputs an error which says `Error: C5.0 models require a factor outcome`,

```
credit <- read.csv("credit.csv")
RNGversion("3.5.2"); set.seed(123)

train_sample <- sample(1000, 900)

credit_train <- credit[train_sample,]
credit_test <- credit[-train_sample,]

prop.table(table(credit_train$default))
prop.table(table(credit_test$default))

credit_model <- C5.0(credit_train[-17], credit_train$default)
```

If we could add a line before calling the `C5.0` function something like `credit_train$default <- as.factor(credit_train$default)` as to not get this error that would be great! Thanks!

**Comment by dataspelunking** [comment]
Greetings! R version 4.0 changed the default behavior of the `read.csv()` function so that `stringsAsFactors = FALSE` is now the default, which unfortunately, broke the code as shown in the book.

However, the current version of the code on GitHub _does_ work correctly, as line 14 has `credit <- read.csv("credit.csv", stringsAsFactors = TRUE)`. This change was made on the November 23, 2020 commit. 

Glad to see you knew the solution to the error message regardless. Thanks for the comment!
